version: "3"
services:
  node-app:
    # Builds from dockerfile
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env

  # Other services