version: "3"
services:
  node-app:
    build:
      context: .
      # args getting passed into dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js